AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Template de desenvolvimento para o projeto ColaAqui.
  Cria a tabela no DynamoDB e os buckets S3 necessários para a aplicação.

Resources:
  # --- Tabela do DynamoDB para armazenar os metadados dos conteúdos ---
  ContentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ColaAquiContents"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: "expiresAt"
        Enabled: true

  # --- Bucket S3 para hospedar o frontend estático (React/Vite) ---
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "colaaqui-frontend-bucket"
      AccessControl: PublicRead # Permite que o conteúdo seja lido publicamente
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html" # Essencial para o roteamento de SPAs (React Router)

  # Política para tornar o bucket do frontend publicamente acessível
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref FrontendBucket, "/*"]]

  # --- Bucket S3 para armazenar os arquivos de conteúdo (pastes) ---
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "colaaqui-storage-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ContentsTableName:
    Value: !Ref ContentsTable
    Description: "Nome da tabela DynamoDB"
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Description: "Nome do bucket S3 para o frontend"
  StorageBucketName:
    Value: !Ref StorageBucket
    Description: "Nome do bucket S3 para armazenamento de conteúdo"