services:
  localstack:
    container_name: localstack-colaaqui
    image: localstack/localstack
    ports: 
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack"

volumes:
  localstack_data: